set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

include_directories( ${CMAKE_CURRENT_BINARY_DIR}/include )
link_directories( ${CMAKE_CURRENT_BINARY_DIR}/lib )

make_directory( ${CMAKE_BINARY_DIR}/include )
